apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://host.docker.internal:8200"
      path: "org/kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "demo"
          key: "token"
